### ISSUE TITLE
OpenCV3 python calls to FlannBasedMatcher::knnMatch fail with error

### ISSUE THREAD

**Issue by Algomorph** [Itseez/opencv#5667] opened 2015-11-13 21:02 UTC
The following code returns an error.
```python
    sift = x2d.SIFT_create(1000)
    features_l, des_l = sift.detectAndCompute(im_l, None)
    features_r, des_r = sift.detectAndCompute(im_r, None)
    
    FLANN_INDEX_KDTREE = 1
    index_params = dict(algorithm=FLANN_INDEX_KDTREE, trees=5)
    search_params = dict(checks=50)
    flann = cv2.FlannBasedMatcher(index_params,search_params)
```
The error returned:
```
opencv/modules/python/src2/cv2.cpp:161: error: (-215) The data should normally be NULL! in function allocate
```
I tried this with Python 2.7.
FLANN_INDEX_KDTREE is set to 1 unlike [here](http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_feature2d/py_matcher/py_matcher.html#matcher),
since in modules/flann/include/opencv2/flann/defines.h I found it set to 1 on line 84.

**Comment by irwincollin** [comment] 2016-01-02 18:22
Have you found a fix to this? I am new to not only openCV but also to python. I am using python 2.7.11, numpy 1.10.2 superpack for python 2.7, scipy 0.16.1 superpack for python 2.7, and openCV 3.1.

I am trying to run a simple script as follows:
```python
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
cv2.namedWindow("Original",1)
cv2.namedWindow("Foreground",1)
bgs = cv2.createBackgroundSubtractorMOG2()

while(1):
    img = cap.read()[1]
    if img is not None:
        img = cv2.resize(img, (0,0), fx=0.1, fy=0.1)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        img = cv2.equalizeHist(img)
        cv2.imshow("Original",img)
        fgmask = bgs.apply(img)
        foreground = cv2.bitwise_and(img,img,mask=fgmask)
        cv2.imshow("Foreground",foreground)
        k = cv2.waitKey(30) & 0xff
        if k == 27:
            break

cap.release()
cv2.destroyAllWindows()
```

The error is as follows:

OpenCV Error: Assertion failed (The data should normally be NULL!) in NumpyAllocator::allocate, file C:\builds\master_PackSlaveAddon-win32-vc12-static\opencv\modules\python\src2\cv2.cpp, line 163
Traceback (most recent call last):
  File "backgroundsub.py", line 16, in <module>
    fgmask = bgs.apply(img)
cv2.error: C:\builds\master_PackSlaveAddon-win32-vc12-static\opencv\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate


Thank you in advance!

**Comment by Algomorph** [comment] 2016-01-02 23:38
@irwincollin I'm aftraid the only way to fix this is to tinker with opencv's python bindings. For now, if you are not OK with downgrading, I suggest writing your app in C++: looking at the number of open C++ bugs for OpenCV 3, I doubt anyone will start addressing binding problems any time soon. Alternatively, you can tinker OpenCV 3 source to try to find the source of the error using print / cout statements and recompiling every time (I'm unaware of any other way to do it when you're calling the code from python). Looking at cv2.cpp, line 163 is a good way to start.

**Comment by webdevbyjoss** [comment] 2016-01-09 01:27
subscribing, got the same error today:
OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /home/username/opt/opencv/modules/python/src2/cv2.cpp, line 163

**Comment by thelunararmy** [comment] 2016-01-11 12:34
Getting the same problem. OS X, Python 2.7.11, OpenCV 3.1.0:

OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /Users/ooo/opencv/modules/python/src2/cv2.cpp, line 163
Traceback (most recent call last):
  File "/Users/ooo/Documents/EclipseWorkspace/BackgroundKiller2/main.py", line 139, in <module>
    flannMatches = flann.knnMatch(des,descam,k=2)
cv2.error: /Users/ooo/opencv/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate

**Comment by hmischel** [comment] 2016-01-13 02:39
I too am getting this error :(
I will try the downgrade to opencv 2.4

**Comment by ehrenbrav** [comment] 2016-01-13 05:40
Same issue... Linux, 2.7.9, openCV 3.1.0-dev

**Comment by hmischel** [comment] 2016-01-13 10:58
This bug looks like it's been around for a couple months.

I guess that does not bode well.

I'll have to find that line of code and try commenting it out.

I guess that's the downside of open source.

Is there a bug fix roadmap to see an estimated time to fix?

**Comment by alalek** [comment] 2016-01-13 11:01
Could someone check OpenCV build with `-DWITH_OPENCL=OFF` CMake parameter?

**Comment by hmischel** [comment] 2016-01-13 11:54
I am using cmake gui.

 

I tried this. I am not sure if this is what you were asking for since I am fairly new to C++/Python.

 

No luck though.

**Comment by ehrenbrav** [comment] 2016-01-13 17:59
I built with -DWITH_OPENCL=OFF and confirmed this does not solve the issue.

**Comment by hmischel** [comment] 2016-01-13 18:29
I took the earlier advice of commenting out that bracket of code cv2.cpp, and have been running successfully since then.

 

It’s a hack, but my project is moving along.

**Comment by ehrenbrav** [comment] 2016-01-13 18:39
That's what I did too. 

I maintain this is a perfectly valid engineering solution: when you're getting a strange error message that is disrupting your work...disable the error message!

**Comment by Algomorph** [comment] 2016-01-13 19:47
@ehrenbrav What you guys did was not just disabling the error message, but also disabling the check whose failure was causing the message. The check was probably there for a reason, it is still unclear to me who put it there or why (would need to dig through git commit history), but "data not being null" is potentially causing a memory leak somewhere, so watch out for that.

**Comment by patricksnape** [comment] 2016-01-22 09:32
That particular Numpy allocation commit (the ``data != 0`` check) is from [this commit](https://github.com/Itseez/opencv/commit/6da5d2133180e3a819e64dcec37692db2309d757) and has been there since November 30, 2013 and was merged in #1901 - so it isn't actually because of that commit and you definitely shouldn't be disabling it.

It looks more likely that the FLANN bindings have been changed and this has caused some memory to get allocated that previously wasn't.

**Comment by hmischel** [comment] 2016-01-22 10:46
Hi Patrick,

 

So that leaves us between a rock and hard place as the saying goes.

If we don’t comment out that line of code, then it is not possible to use Flann with python.

 

The alternative would be to use SURF, which rumor has it costs 20K to license.

Or to use C++ or EMGU. That’s not really viable when the application requirements from the client specify Python.

 

Perhaps I am missing something obvious, but unless there is another option, I don’t really see an alternative to commenting out that line of code.

 

Herb

**Comment by patricksnape** [comment] 2016-01-22 10:54
@hmischel I'm just saying - don't be surprised if you have a massive memory leak or something isn't computing what you think it is! I think that the offending line is being hit because something weird is happening. I can't replicate the issue for ``createBackgroundSubtractorMOG2``, but I can replicate it for ``FlannBasedMatcher``.

Something fishy is happening though - for example, the code passes if you do ``matches = flann.knnMatch(des1, 2)`` rather than ``matches = flann.knnMatch(des1, des2, 2)``.

My gut feeling is that something weird is happening with the bindings and the fact that ``knnMatch`` is overloaded is the problem. Perhaps passing the second argument, which in the C++ API could map to the output matches vector, is somehow getting interpreted as the output vector in Python (which is expected to be an empty array?).

**Comment by Dikay900** [comment] 2016-01-22 12:33
just wanna make sure this bug was introduced with on the 3.1 release? 3.0 works fine?

**Comment by Algomorph** [comment] 2016-01-22 16:40
@Dikay900 , I reported it back in 3.0, so I don't think 3.0 (or 3.0 beta) will work.

**Comment by Dikay900** [comment] 2016-01-22 19:52
all posted snippets are working with latest master on windows 10 with Python 3.5 and Python 2.7.11 with latest numpy compiled and installed.
@Algomorph you are also working on Linux i guess?

**Comment by patricksnape** [comment] 2016-01-23 00:15
I believe that the patch [here](https://gist.github.com/patricksnape/72d964c2bf9b046513ab) fixes this issue for the `FlannBasedMatcher`. It would be great if someone could verify. This is obviously code but I just wanted to try get something for @hmischel et. al. who just want to get on with their work. If someone can confirm this works for me I will create a clean PR.

My instinct was that ``BFMatcher`` worked, but ``FlannBasedMatcher `` did not (and only in the case of passing training descriptors). So, in looking at the differences between their code, I saw that ``add`` was overloaded for `FlannBasedMatcher ` and that the accessing of the `descriptors_` was following a different pattern - merely following the pattern seemed to fix it!

**Comment by Dikay900** [comment] 2016-01-23 09:21
I applied this commit here which was already rejected 26d9a7cd400921b4c2b2bc6ecafd30873d848084 in #4111 so you can simply cherry-pick this commit.

This works as intended and does not seem to break functionality or T-API compatibility in general so i would think this is a hacky but valid fix. Would like to see what the opencv devs are saying.
:+1:

**Comment by patricksnape** [comment] 2016-01-23 11:11
@dikay900 ah right, that is essentially exactly the same as my fix! Some variant of this definitely needs to be merged in. I'm fine to do a PR if an opencv dev can weigh in.

**Comment by patricksnape** [comment] 2016-01-23 15:47
Actually, @Dikay900, 26d9a7c seems wrong to me, given the other `add` logic. From what I can understand from browsing the source code, if you call `getMatVector` on an `InputArray` (which ultimately is what is passed to `add` via `knnMatch`), and then `InputArray` is actually of type `MAT`, then each column of the Matrix is added as an element to the vector. Whereas, if you call `getMatVector` and `InputArray` represents a `STD_VECTOR_MAT` then each element represents an entire Matrix, which seems more correct. Given the logic of the `DescriptorMatcher::add`, it seems that either a vector of Matrices or a single Matrix is expected, and thus you can't just call `getMatVector` as is done in that commit. You need to do as I did in my gist.

**Comment by colinmccormick** [comment] 2016-02-01 17:56
Getting the same error: OSX 10.11.13, Python 2.7.11, OpenCV 3.1. @patricksnape I tried your patch to matchers.cpp and rebuilt, but still got the same error.

**Comment by patricksnape** [comment] 2016-02-01 21:48
@colinmccormick Which patch - the one provided by my PR #6009? I tried my patch on OSX and Linux, 3.5 and 2.7 and it seemed to work for me :worried:

**Comment by colinmccormick** [comment] 2016-02-02 15:13
@patricksnape I tried your patch (PR #6009) again and rebuilt, and this time it worked. (Not sure what I did wrong the first time.) Error is resolved, so thanks!

**Comment by alalek** [comment] 2016-02-02 16:05
Thanks @patricksnape !

**Closed by alalek** 2016-02-02 16:05 UTC
Labels: affected: master, bug, category: flann, category: python bindings, category: t-api, priority: normal

**Comment by hmischel** [comment] 2016-02-03 01:30
Thank you!

**Comment by ro-mathew** [comment] 2016-02-04 03:19
Thanks @patricksnape

**Comment by NEMANJA-ILIC** [comment] 2016-02-07 21:09
Could someone please walk me through the process of applying this patch? I'm running python 2.7.6 with opencv 3.1.0-dev  on Ubuntu 14.04?

Do I need to remove anything prior to doing this or just compile and run?

Thanks in advance for the help!

**Comment by shu1995shijia** [comment] 2016-02-15 23:56
Try use other descriptor other feature descriptor called "AKAZE" (from Opencv 3.0.0 I believe) which could do the same job as the ORB. I am using opencv 3.1.0 by the way.

**Comment by ZhengRui** [comment] 2016-03-02 15:49
Thanks @patricksnape the fix works :+1:

**Comment by junostar** [comment] 2016-03-08 02:56
Tried the above code on Python 2.7.9, OpenCV 3.1.0 and it generates the NULL error. I reverted back to OpenCV 3.0 and it is working again.

**Comment by patricksnape** [comment] 2016-03-08 09:54
@junostar - which code generated the error? And did you apply my patch?

**Comment by junostar** [comment] 2016-03-08 15:05
@patricksnape - Sorry I didn't see there were two different code snippets. I'm talking about calling `fgmask = bgs.apply(img)` with the `cv2.createBackgroundSubtractorMOG2()`. I didn't apply the fix because I have to deploy my software that uses OpenCV to people and I can't expect them to manually go in and fix the bug. I will have to wait for the next version and hopefully it gets picked up...

**Comment by patricksnape** [comment] 2016-03-08 15:44
@junostar Right. Well given that this thread is closed you should probably create a new issue showing that you still seeing ``cv2.createBackgroundSubtractorMOG2()`` as failing (I could never actually replicate this). You will also probably want to give detailed information about all the flags that were on during building as well as your operating system and compiler so that we can try and replicate your error. It's essentially impossible to fix these things without being able to replicate them!

**Comment by junostar** [comment] 2016-03-08 15:47
@patricksnape - Ok, thanks I will look into doing that! FYI, I didn't build OpenCV 3.1 from source, it was the pre-compiled binary from the official repo that fails...

**Comment by Filarius** [comment] 2016-03-20 19:39
Same here, Windows 7, Python 3.4.1, OpenCV 3.1.0
while trying to use Stitcher.stitch()

**Comment by benjimin** [comment] 2016-05-27 04:07
I've replicated this error, using opencv 3.1.0 on Linux.

OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /.../opencv-3.1.0/modules/python/src2/cv2.cpp, line **163**

Additionally, I found that calling cv2.FlannBasedMatcher() without arguments produces a segfault (I was expecting it to instead choose default parameters).

**Comment by mobcdi** [comment] 2016-06-10 13:05
Is there a workaround for this error so FLANN matching can be used in python for those not able to edit the source code and need to stick on version 3.1 not nightly builds?

**Comment by Murtaza0xFF** [comment] 2016-06-17 22:21
Has the PR been merged?

**Comment by adityapatadia** [comment] 2016-09-01 18:05
Any update on this?

**Comment by NEMANJA-ILIC** [comment] 2016-09-01 18:32
Did you build from source? It should be fixed as I have used it on one of my projects.

**Comment by adityapatadia** [comment] 2016-09-01 18:41
I applied patch in homebrew but new version release to fix this will be appreciated.

**Comment by fmw42** [comment] 2016-09-02 00:27
Does any one know if this has been fixed yet in a downloadable version of OpenCV 3.1.0_x and if so what is the minor version number?

**Comment by benjimin** [comment] 2016-09-02 00:40
@fmw42, following the links here, it looks like a fix was merged in April, but there has not been any new release tagged since December (3.1.0), so I think you're asking for 3.1.1 to be created.

**Comment by fmw42** [comment] 2016-09-02 01:27
I get my downloads from MacPorts and it has OpenCV 3.1.0_3 (only). So I was hoping there might have been a newer minor release that would include that patch. How often are versions released from OpenCV?  What are the policies that drive when a new version is released?

**Comment by moof2k** [comment] 2016-12-05 05:42
Also seeing this with the ORB feature compute function @ c48d7f86b:

    orb = cv2.ORB_create()
    kp = orb.detect(image, None)
    kp, des = orb.compute(image, kp)
    ...
    error: (-215) The data should normally be NULL! in function allocate

**Comment by djshaji** [comment] 2017-02-02 13:05
Can confirm, error occurs with ORB as well:
`matches = flann.knnMatch(des1,des2, k=2)
cv2.error: /builddir/build/BUILD/opencv-3.1.0/modules/python/src2/cv2.cpp:163: error: (-215) The data should normally be NULL! in function allocate`

**Comment by mm-manu** [comment] 2017-02-23 15:23
still no official fix? :(

**Comment by slimway** [comment] 2017-04-27 13:35
hello sir, i used your solution and the error is fixed, however the flann can't find any matches even in the same images

**Comment by niyazpk** [comment] 2017-09-08 19:51
Even after setting:
 cv2.ocl.setUseOpenCL(False)
I am getting the same error.

python: 3.6.2
opencv 3.1.0

**Comment by benjimin** [comment] 2017-09-11 00:28
@niyazpk could you try testing the latest opencv release? (Currently 3.3 as of a month ago.)

**Comment by niyazpk** [comment] 2017-09-12 03:03
I was not able to make OpenCV 3.3 work with my conda ENV. Some issues with Openblas etc.

So I tried my code on a new docker image with OpenCV 3.3. It worked fine. Thanks!

**Comment by lavinachitara** [comment] 2017-11-29 09:55
Yeah, earlier I was also facing the same issue but after installing opencv contrib it is working without any error
`pip install opencv-contrib-python`

**Comment by Motherboard** [comment] 2018-02-14 08:48
@lavinachitara This solved it for me as well.

**Comment by mailshubham1996** [comment] 2018-06-16 10:30
@lavinachitara  that was awwsome...
