### ISSUE TITLE
GCC 6.0/6.x build problems

### ISSUE THREAD

**Issue by samtux** [Itseez/opencv#6517] opened 2016-05-10 01:34 UTC
I get the next error compiling Opencv v2.4.12 in Arch linux https://aur.archlinux.org/packages/opencv2/:

---
[ 0%] Built target opencv_core_pch_dephelp
[ 0%] Generating precomp.hpp.gch/opencv_core_Release.gch
cc1plus: aviso: la opción de línea de órdenes ‘-Wmissing-prototypes’ es válida para C/ObjC pero no para C++
cc1plus: aviso: la opción de línea de órdenes ‘-Wstrict-prototypes’ es válida para C/ObjC pero no para C++
In file included from /usr/include/c++/6.1.1/bits/stl_algo.h:59:0,
from /usr/include/c++/6.1.1/algorithm:62,
from /tmp/packerbuild-1001/opencv2/opencv2/src/opencv-2.4.12.3/modules/core/include/opencv2/core/core.hpp:53,
**from /tmp/packerbuild-1001/opencv2/opencv2/src/opencv-2.4.12.3/modules/core/precomp.hpp:48:
/usr/include/c++/6.1.1/cstdlib:75:25: error fatal: stdlib.h: No existe el fichero o el directorio**
#include_next <stdlib.h>
^
compilación terminada.
modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:62: fallo en las instrucciones para el objetivo 'modules/core/precomp.hpp.gch/opencv_core_Release.gch'
make[2]: *** [modules/core/precomp.hpp.gch/opencv_core_Release.gch] Error 1
CMakeFiles/Makefile2:862: fallo en las instrucciones para el objetivo 'modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all'
make[1]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
Makefile:160: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

---

**Comment by StevenPuttemans** [comment] 2016-05-10 07:12
Hello there. Let me give you some pointers here

- Spanish error output won't help you get a solution fast. The main language supported here is English, so sometimes simply translating the whole block could help out.
- Could you please provide us with the full CMAKE output and the configuration you are using?
- To me it seems that your system does not recognize the standard C++ compiler libraries. So could you check which gcc or g++ compiler is installed on your system?

**Comment by alalek** [comment] 2016-05-10 07:51
> /usr/include/c++/6.1.1/cstdlib:75:25: error fatal: stdlib.h

Both headers are "system" so I agree with @StevenPuttemans and I believe there is nothing to fix in OpenCV directly.
Could you should check your C/C++ compiler and C++ developer library (try to compile some little program with `#include <algorithm>`).

**Comment by reisub-de** [comment] 2016-05-10 10:05
Here is the error message in english:
```
[  1%] Generating precomp.hpp
[  1%] Generating precomp.hpp.gch/opencv_core_Release.gch
In file included from /usr/include/c++/6.1.1/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6.1.1/algorithm:62,
                 from /home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/core/include/opencv2/core/core.hpp:53,
                 from /home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/core/precomp.hpp:48:
/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:62: recipe for target 'modules/core/precomp.hpp.gch/opencv_core_Release.gch' failed
make[2]: *** [modules/core/precomp.hpp.gch/opencv_core_Release.gch] Error 1
CMakeFiles/Makefile2:862: recipe for target 'modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

This is a behaviour change in GCC 6.1 for -isystem includes
See [https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129) closed as WONTFIX
Sadly, I'm not that good with complex include dependencies, but I think this should be fixed to be compatible with upcoming gcc releases

**Comment by alalek** [comment] 2016-05-10 11:01
@reisub-de Thanks for investigation!

We build OpenCV with enabled warnings (`-Wall`) to detect possible problems in the contributed code.
And we use `-isystem` to suppress warnings from 3rdparty includes (there is no way to fix them).

> All warnings, other than those generated by ‘#warning’ (see Diagnostics), are suppressed while GCC is processing a system header

https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

Second reason is problem with some system-wide pre-installed OpenCV packages which put their includes into /usr/include/ directly ([Ubuntu](http://packages.ubuntu.com/xenial/amd64/libopencv-core-dev/filelist), [Fedora](https://apps.fedoraproject.org/packages/opencv-devel/contents/) and many others). Also OpenCV may use some 3rdparty library which INCLUDE_DIR is /usr/include/ and put it into include directories list for compiler. And when OpenCV sources may use mismatched system-wide OpenCV headers...
Unfortunately, current build scripts doesn't provide reliable way to manage include directories order, so some terrible things may arrive (like #6403).
With `-isystem` we "put" all 3rdparty include directories after OpenCV directories (which are handled with "-I").

> All directories named by -isystem are searched after all directories named by -I, no matter what their order was on the command line.

The same link: https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

@reisub-de Could you try this [hack](https://github.com/Itseez/opencv/issues/6508#issuecomment-217136023) with GCC 6.1?

**Comment by reisub-de** [comment] 2016-05-10 12:55
@alalek Ahh, that makes sense

I tried the workaround but it doesn't change it, I get the exact same error message. It looks like the `-I` for system includes is not applied everywhere (A grep for `-isystem` still finds some occurences but not as many as without the workaround.

A (hacky) solution I came up with is this:
```
--- opencv-2.4.12.3/cmake/OpenCVPCHSupport.cmake
+++ opencv-2.4.12.3-patched/cmake/OpenCVPCHSupport.cmake
@@ -24,7 +24,7 @@
     ENDIF()
 
     SET(_PCH_include_prefix "-I")
-    SET(_PCH_isystem_prefix "-isystem")
+    SET(_PCH_isystem_prefix "-I")
     SET(_PCH_define_prefix "-D")
 
 ELSEIF(CMAKE_GENERATOR MATCHES "^Visual.*$")
```
Now it fails much later in the compile process with
```
[ 47%] Building CXX object modules/contrib/CMakeFiles/opencv_contrib.dir/src/chamfermatching.cpp.o
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp: In member
 function ‘void cv::ChamferMatcher::Matching::computeDistanceTransform(cv::Mat&, cv::Mat&, cv::Mat&
, float, float, float)’:
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:969:30: er
ror: the compiler can assume that the address of ‘annotate_img’ will never be NULL [-Werror=address
]
             if (&annotate_img!=NULL) {
                              ^
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1016:34: e
rror: the compiler can assume that the address of ‘annotate_img’ will never be NULL [-Werror=addres
s]
                 if (&annotate_img!=NULL) {
                                  ^
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp: In member
 function ‘cv::ChamferMatcher::Match* cv::ChamferMatcher::Matching::localChamferDistance(cv::Point,
 cv::Mat&, cv::Mat&, cv::ChamferMatcher::Template*, float)’:
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1111:25: e
rror: the compiler can assume that the address of ‘orientation_img’ will never be NULL [-Werror=add
ress]
     if (&orientation_img!=NULL) {
                         ^
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1111:5: wa
rning: nonnull argument ‘orientation_img’ compared to NULL [-Wnonnull-compare]
     if (&orientation_img!=NULL) {
     ^~
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp: In member
 function ‘void cv::ChamferMatcher::Matching::computeDistanceTransform(cv::Mat&, cv::Mat&, cv::Mat&
, float, float, float)’:
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:1016:17: w
arning: nonnull argument ‘annotate_img’ compared to NULL [-Wnonnull-compare]
                 if (&annotate_img!=NULL) {
                 ^~
/home/user/build/opencv2_2/src/opencv-2.4.12.3/modules/contrib/src/chamfermatching.cpp:969:13: wa
rning: nonnull argument ‘annotate_img’ compared to NULL [-Wnonnull-compare]
             if (&annotate_img!=NULL) {
             ^~
cc1plus: some warnings being treated as errors
modules/contrib/CMakeFiles/opencv_contrib.dir/build.make:158: recipe for target 'modules/contrib/CM
akeFiles/opencv_contrib.dir/src/chamfermatching.cpp.o' failed
make[2]: *** [modules/contrib/CMakeFiles/opencv_contrib.dir/src/chamfermatching.cpp.o] Error 1
CMakeFiles/Makefile2:2711: recipe for target 'modules/contrib/CMakeFiles/opencv_contrib.dir/all' fa
iled
make[1]: *** [modules/contrib/CMakeFiles/opencv_contrib.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by reisub-de** [comment] 2016-05-10 17:24
That last error was fixed [here](https://github.com/Itseez/opencv/commit/eebd4cad665f4f1270ca58bb13e9708e130f9b30#diff-70c6e149320b4e01b1b89a854662861a) in #5674, after cherrypicking this to 2.4.12.3 it compiles fine with the aforementioned hack.

**Comment by alalek** [comment] 2016-05-10 17:41
Thanks for update! I will try to create some workaround for this problem.

**Comment by samtux** [comment] 2016-05-11 21:48
I've already solved the installation with solution applied in the [Arch Linux package](https://aur.archlinux.org/packages/opencv2/). 

Thank you very much for the answers.

**Comment by reisub-de** [comment] 2016-05-11 22:59
@alalek @samtux 
This should be reopened until opencv itself is patched

**Comment by TheodoreT** [comment] 2016-05-12 15:28
I can confirm that this issue affects also the master version

**Comment by alalek** [comment] 2016-05-14 13:13
This workaround works in some cases (see #6541): `cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`

**Comment by reisub-de** [comment] 2016-05-14 14:16
Ok, this works for me. It's just that compile time goes up from ~2 minutes to ~ 3 minutes (first world problems :D )

**Closed** 2016-05-16 13:12 UTC
Labels: affected: 2.4, affected: master, bug, category: build/install

**Comment by abrock** [comment] 2017-02-03 23:53
I had the same problem and fixed it by setting

ENABLE_PRECOMPILED_HEADERS

to "Off" and adding  "-fPIC" to

CMAKE_C_FLAGS and CMAKE_CXX_FLAGS

**Comment by ChristofKaufmann** [comment] 2017-03-09 14:37
I can confirm this. I encounter this as well on Ubuntu 16.10, gcc 6.2.0 (default) and the default setting (on) for precompiled headers. So following the [tutorial](http://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html) for building OpenCV does not work for me. Switching precompiled headers off helps. Alternatively exchanging the `-isystem` options with `-I` in cmake/OpenCVPCHSupport.cmake, as suggested by the [comment above](https://github.com/opencv/opencv/issues/6517#issuecomment-218148574) also works. I believe, I could sort this out in an acceptable way and I'm going to prepare a patch / PR.

**Comment by drkurrey** [comment] 2017-04-20 09:17
In my case, I simply removed "_next" from #include_next <stdlib.h> which was mentioned in file cstdlib.
Also from #inlude_next <math.h> mentioned in file cmath. Previously mentioned files can be found in /usr/include/c++/6/.

**Comment by retg96** [comment] 2019-04-24 00:04
Help me!!


In which file should I put the following line cmake -DENABLE_PRECOMPILED_HEADERS = OFF?

And In which folder do I find that file?

**Comment by retg96** [comment] 2019-04-24 00:23
I tryed to install opencv in a raspberry pi 3, and I get the following error:

from /home/pi/opencv-3.1.0/build/modules/core/precomp.hpp:49:
/usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: There is no file or directory
#include_next

and I don´t know how to fix it.

**Comment by drkurrey** [comment] 2019-04-24 16:04
It exists

**Comment by IdamEniIdam** [comment] 2019-08-18 09:15
make COMPIL_ENV=64 
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/GLOG'
building libMorphoGlog.so.1.0
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/GLOG'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/driver'
building libMSO_Drv.so.6.14.5.0
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/driver'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/MSO100'
building libMSO100.so.6.14.5.0
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/MSO100'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/wrapper'
[AR] libwrapper.a
ar: `u' modifier ignored since `D' is the default (see `U')
r - obj64/MORPHO_WRAPPER.o
r - obj64/MORPHO_WRAPPER_MSO.o
r - obj64/MORPHO_WRAPPER_CBI.o
r - obj64/MORPHO_WRAPPER_Idle.o
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/wrapper'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/sdk'
building libmorphosdk.so.6.14.5.0
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/sdk'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/native'
building libMorphoSmartSDKJavaWrapper.so.6.14.5.0
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/native'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/java'
building SDK Java Wrapper Archive
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/java'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/MorphoSmartJavaSample'
building MorphoSmart SDK Java Sample Archive
Buildfile: /home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk/JavaWrapper/MorphoSmartJavaSample/build.xml

Compile:

Build:
      [jar] Building jar: /home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/build/bin/MorphoSmartJavaWrapperSample.jar

BUILD SUCCESSFUL
Total time: 1 second
cp ../../../Sdk/JavaWrapper/MorphoSmartJavaSample/run.sh ../../build/bin/
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/JavaWrapper/MorphoSmartJavaSample'
cp -f LibMSOCS/libmsocs.so.6.6 build/lib64/
ln -sf libmsocs.so.6.6 build/lib64/libmsocs.so.6
ln -sf libmsocs.so.6.6 build/lib64/libmsocs.so
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir'
make[2]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/source'
make[2]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/source'
make[2]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples'
make[3]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples/isofirbuilder'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples/isofirbuilder'
make[3]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples/isofirextractor'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples/isofirextractor'
make[2]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir/samples'
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/SDK_Addons/libisofir'
make[1]: Entering directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/samples'
[C++] SDK_Sample/sample_sdk.cpp
g++ -c -O3 -Wall -Wno-unused-result -D_MSO_LIB -DLINUX -DHOST   SDK_Sample/sample_sdk.cpp -o SDK_Sample/sample_sdk.o
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from SDK_Sample/sample_sdk.cpp:10:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
Makefile:73: recipe for target 'SDK_Sample/sample_sdk.o' failed
make[1]: *** [SDK_Sample/sample_sdk.o] Error 1
make[1]: Leaving directory '/home/idam/Documents/MorphoSmart_SDK_6.14.5.0_linux/PC/Sdk_linux/samples'
Makefile:88: recipe for target 'bin' failed
make: *** [bin] Error 1

**Comment by IdamEniIdam** [comment] 2019-08-18 09:16
Please any help from the error above... Thank you
