### ISSUE TITLE
opencv3.10 does not support cuda8.0rc? 

### ISSUE THREAD

**Issue by zxfzqf** [Itseez/opencv#6677] opened 2016-06-14 06:09 UTC
- OpenCV version: 3.10
- Host OS: Ubuntu 16.04 amd64
### In which part of the OpenCV library you got the issue?
I have installed CUDA 8.0RC，Error when build opencv3.10，But opencv2.4.13 is normal. 
I have noticed that the release time of opencv3.10 is 2015-12-21，Cuda8.0rc release time is about 2016.05,opencv2.4.13  release time is 2016-05-19,I would like to confirm,  opencv3.10 does not support cuda8.0rc? 

 Compile error ：

``
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:120:54: error: ‘NppiGraphcutState’ has not been declared
     typedef NppStatus (*init_func_t)(NppiSize oSize, NppiGraphcutState** ppStat
                                                      ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:135:18: error: ‘NppiGraphcutState’ does not name a type
         operator NppiGraphcutState*()
                  ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:141:9: error: ‘NppiGraphcutState’ does not name a type
         NppiGraphcutState* pState;
         ^
In file included from /home/ecarx/opencv-3.1.0/build/modules/cudalegacy/precomp.hpp:75:0:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp: In constructor ‘{anonymous}::NppiGraphcutStateHandler::NppiGraphcutStateHandler(NppiSize, Npp8u*, {anonymous}::init_func_t)’:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:127:39: error: ‘pState’ was not declared in this scope
             nppSafeCall( func(sznpp, &pState, pDeviceMem) );
                                       ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp: In destructor ‘{anonymous}::NppiGraphcutStateHandler::~NppiGraphcutStateHandler()’:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:132:43: error: ‘pState’ was not declared in this scope
             nppSafeCall( nppiGraphcutFree(pState) );
                                           ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:132:49: error: ‘nppiGraphcutFree’ was not declared in this scope
             nppSafeCall( nppiGraphcutFree(pState) );
                                                 ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp: In function ‘void cv::cuda::graphcut(cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::Stream&)’:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:174:51: error: ‘nppiGraphcutGetSize’ was not declared in this scope
     nppSafeCall( nppiGraphcutGetSize(sznpp, &bufsz) );
                                                   ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:182:61: error: ‘nppiGraphcutInitAlloc’ was not declared in this scope
     NppiGraphcutStateHandler state(sznpp, buf.ptr<Npp8u>(), nppiGraphcutInitAll
                                                             ^
In file included from /home/ecarx/opencv-3.1.0/build/modules/cudalegacy/precomp.hpp:75:0:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:191:146: error: ‘nppiGraphcut_32s8u’ was not declared in this scope
 nsp.step), sznpp, labels.ptr<Npp8u>(), static_cast<int>(labels.step), state) );
                                                                            ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:196:146: error: ‘nppiGraphcut_32f8u’ was not declared in this scope
 nsp.step), sznpp, labels.ptr<Npp8u>(), static_cast<int>(labels.step), state) );
                                                                            ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp: In function ‘void cv::cuda::graphcut(cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::Stream&)’:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:246:52: error: ‘nppiGraphcut8GetSize’ was not declared in this scope
     nppSafeCall( nppiGraphcut8GetSize(sznpp, &bufsz) );
                                                    ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:254:61: error: ‘nppiGraphcut8InitAlloc’ was not declared in this scope
     NppiGraphcutStateHandler state(sznpp, buf.ptr<Npp8u>(), nppiGraphcut8InitAl
                                                             ^
In file included from /home/ecarx/opencv-3.1.0/build/modules/cudalegacy/precomp.hpp:75:0:
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:267:146: error: ‘nppiGraphcut8_32s8u’ was not declared in this scope
 nsp.step), sznpp, labels.ptr<Npp8u>(), static_cast<int>(labels.step), state) );
                                                                            ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
/home/ecarx/opencv-3.1.0/modules/cudalegacy/src/graphcuts.cpp:274:146: error: ‘nppiGraphcut8_32f8u’ was not declared in this scope
 nsp.step), sznpp, labels.ptr<Npp8u>(), static_cast<int>(labels.step), state) );
                                                                            ^
/home/ecarx/opencv-3.1.0/modules/core/include/opencv2/core/private.cuda.hpp:165:52: note: in definition of macro ‘nppSafeCall’
 #define nppSafeCall(expr)  cv::cuda::checkNppError(expr, __FILE__, __LINE__, CV
                                                    ^
modules/cudalegacy/CMakeFiles/opencv_cudalegacy.dir/build.make:290: recipe for target 'modules/cudalegacy/CMakeFiles/opencv_cudalegacy.dir/src/graphcuts.cpp.o' failed
make[2]: *** [modules/cudalegacy/CMakeFiles/opencv_cudalegacy.dir/src/graphcuts.cpp.o] Error 1

**Comment by raldam** [comment] 2016-06-15 08:12
I have the same problem, I installed opencv3-1 without Cuda for now since I don't really need it. But, it would be preferable if I could use GPU accelerated algorithms for video reading and writing.  Waiting for a solution.

**Comment by jet47** [comment] 2016-06-15 08:44
CUDA 8.0 support was fixed in master branch : https://github.com/Itseez/opencv/pull/6510

**Comment by raldam** [comment] 2016-06-15 19:04
Worked like a charm, thank you :)

**Closed** 2016-06-15 20:42 UTC
Labels: category: build/install, category: gpu (cuda)

**Comment by zxfzqf** [comment] 2016-06-16 01:14
Thank you for your help.

**Comment by daveselinger** [comment] 2016-10-24 20:04
For those people who find this page looking for a way to fix this in their build but can't deal with the volatility of MASTER, here's the code I used in my build script

```
cd /opt/opencv-build && \
    git clone https://github.com/Itseez/opencv.git && \
    cd /opt/opencv-build/opencv && \
    git checkout 3.1.0 && \
    git format-patch -1 10896129b39655e19e4e7c529153cb5c2191a1db && \
    git am < 0001-GraphCut-deprecated-in-CUDA-7.5-and-removed-in-8.0.patch && \
```
This script snippet will build a single patch file for that one change, then apply that patch using all git commands. It is opencv 3.1.0 + this bugfix and nothing else.

**Comment by mdaiter** [comment] 2016-11-23 18:09
@daveselinger could we cherry-pick this commit into the 3.1.0 branch or create a 3.1.1 branch? It seems like many users would benefit from having this automatically added to the 3.1.0 branch or checking out a 3.1.1 branch to avoid confusion + Googling for this solution.

**Comment by daveselinger** [comment] 2016-11-23 18:25
@mdaiter Hey dude, I've never done that before, and didn't realize this bug was getting all this attention. I'll submit a PR later today.

**Comment by daveselinger** [comment] 2016-11-23 18:35
@mdaiter It doesn't look like OpenCV does point releases from 3.1, so I don't expect them to make a release entirely based on this patch. Instead, I forked and will keep this up as best I can. Instead of cloning from the base master, use this instead:

```
git clone https://github.com/daveselinger/opencv
git checkout 3.1.0-withcuda8
```

Then continue on your way. Happy OpenCV'ing.

**Comment by Maghoumi** [comment] 2016-11-25 04:11
To correct that, it is `git checkout 3.1.0-with-cuda8` :D

**Comment by vincenttsai2015** [comment] 2016-12-28 12:06
@daveselinger I tried to clone opencv from https://github.com/daveselinger/opencv, but there are error messages while I was using cmake as follows......
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_C_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python2
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3
   used as include directory in directory /home/vincenttsai/opencv/modules/python/python3

-- Configuring incomplete, errors occurred!
See also "/home/vincenttsai/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/home/vincenttsai/opencv/build/CMakeFiles/CMakeError.log".

Is there something to fix or install? Thanks.

**Comment by daveselinger** [comment] 2016-12-28 16:03
@vincenttsai2015 It looks like you do not have the library hdf5-dev installed. Should be pretty easily corrected:

```
sudo apt-get install libhdf5-dev
```
LMK if it works.

**Comment by santhoshkelathodi** [comment] 2016-12-29 04:39
@daveselinger 
When I try to clone I get this error
git clone https://github.com/daveselinger/opencvCloning into 'opencv'...
remote: Counting objects: 195998, done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
 the code is still there?

**Comment by daveselinger** [comment] 2016-12-29 06:10
@santhoshkelathodi Still there. I'd shoot for googling your error. E.g.:

http://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls

**Comment by santhoshkelathodi** [comment] 2016-12-29 10:06
@daveselinger  Thank you very much... 

I directly accessed the branch https://github.com/daveselinger/opencv/tree/3.1.0-with-cuda8 and I was able to install openCV without any error.

Now I am facing issue with running the c++ sample code.  It gives the following run time error:
In fact my desktop machine does not have a GPU. Hence I could not have a driver for NVDIA. Anything specifically needs to be taken care while installing openCV in that case? Or in application I need to disable some macro?

OpenCV Error: Gpu API call (CUDA driver version is insufficient for CUDA runtime version) in allocate, file /home/sk47/opencv_home/opencv/modules/core/src/cuda/gpu_mat.cu, line 71
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/sk47/opencv_home/opencv/modules/core/src/cuda/gpu_mat.cu:71: error: (-217) CUDA driver version is insufficient for CUDA runtime version in function allocate

**Comment by daveselinger** [comment] 2016-12-30 00:19
@santhoshkelathodi Once again, my friend Google is your friend. :)

**Comment by daveselinger** [comment] 2016-12-30 00:21
https://devtalk.nvidia.com/default/topic/962474/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-version/ probably has the right answer. You've either likely installed to low a version of nvidia driver (<367) or installed the CUDA driver incorrectly...

**Comment by santhoshkelathodi** [comment] 2016-12-30 06:11
Thank you for putting it across very nicely about google. I have seen those links and tried to install that way. But inherently they are explaining how to install cuda when GPU is available. It does not address the problem I am facing I don't have a GPU. :(

**Comment by daveselinger** [comment] 2017-01-03 22:22
@santhoshkelathodi Sorry to be the bearer of bad news, then because CUDA is a GPU acceleration platform ONLY for Nvidia GPU's. https://en.wikipedia.org/wiki/CUDA

**Comment by ahsteven** [comment] 2017-03-07 17:24
@daveselinger I cloned the version you posted above:

`git clone https://github.com/daveselinger/opencv
git checkout 3.1.0-with-cuda8
`
Then I tride cmake as follows:
`cmake -D CMAKE_BUILD_TYPE=RELEASE -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=OFF -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_OPENGL=ON -D WITH_V4L=ON -D WITH_CUDA=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_TBB=ON ..`

However I get the error:

 -- ICV: Downloading ippicv_linux_20151201.tgz...
CMake Error at 3rdparty/ippicv/downloader.cmake:73 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/teves/opencv/3rdparty/ippicv/downloads/linux-808b791a6eac9ed78d32a7666804320e/ippicv_linux_20151201.tgz]
      expected hash: [808b791a6eac9ed78d32a7666804320e]
        actual hash: [a045a276288bc6a21d9aacd4eb41b8ea]
             status: [28;"Timeout was reached"]

Any suggestions on this?

**Comment by alalek** [comment] 2017-03-07 17:42
> Timeout was reached

Check network/proxy settings and try again.

**Comment by ahsteven** [comment] 2017-03-07 18:13
@alalek It finally went through.

**Comment by Ivan-Guillermo-Duarte** [comment] 2017-10-01 16:28
Buenas Tardes a todos, tengo este problema, espero que me puedan ayudar, se los agradezco mucho.

[ 59%] Built target example_datasets_or_mnist
make[2]: Warning: File 'modules/java/core+Algorithm.java' has modification time                                                                                         134 s in the future
[ 59%] Generating opencv-310.jar
/usr/lib/jvm/java-7-openjdk-armhf/jre/lib/rt.jar: inflateFully: Unexpected end o                                                                                        f stream

BUILD FAILED
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.jav                                                                                        a:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more

Total time: 0 seconds
java.lang.NoClassDefFoundError: java/math/BigInteger
        at org.apache.tools.ant.types.Resource.getMagicNumber(Resource.java:58)
        at org.apache.tools.ant.types.Resource.<clinit>(Resource.java:48)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.jav                                                                                        a:90)
        at org.apache.tools.ant.Main.runBuild(Main.java:826)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 7 more
java/math/BigInteger
modules/java/CMakeFiles/opencv_java.dir/build.make:12619: recipe for target 'bin                                                                                        /opencv-310.jar' failed
make[2]: *** [bin/opencv-310.jar] Error 1
CMakeFiles/Makefile2:14666: recipe for target 'modules/java/CMakeFiles/opencv_ja                                                                                        va.dir/all' failed
make[1]: *** [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Estoy utilizando el sistema raspbian, en una raspberry pi 1 B

**Comment by Ivan-Guillermo-Duarte** [comment] 2017-10-01 21:34
Hello @alalek , Why did you delete my comment :( 
I need help in that mistake that I have, help me in that, I would thank you very much.

**Comment by alalek** [comment] 2017-10-01 21:57
@Ivan-Guillermo-Duarte Because we are not tolerant about spamming of the [similar](https://github.com/opencv/opencv/issues/5639#issuecomment-332382815) messages, especially into threads of unrelated issues.
This tracker is for issues and bugs that needs fix in OpenCV. But we have no chance to help:
- with problems that we can't reproduce (custom / unsupported platforms or HW/SW configurations)
- with problems with uncompleted/unclear problem descriptions (you definitely need to run this command: `make VERBOSE=1`)
- with remote investigations of build problems in unknown build environments (we have lack of time to do this for each user)

You may find / ask usage questions / help requests at Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Ivan-Guillermo-Duarte** [comment] 2017-10-01 22:09
Muchas Gracias @alalek que pena contigo, si algo te estaré molestando con algunas inquietudes futuras. :) nuevamente muchas gracias, y espero que por si acaso me pudieras ayudar con el problema que habías visto antes. 

En ingles: 

Many thanks @alalek what a shame with you, if anything I'll be bothering you with some future concerns. :) Again thank you very much, and I hope in case you could help me with the problem you had seen before.

**Comment by ebimor** [comment] 2018-01-10 22:49
@daveselinger  thanks much dude :100:

**Comment by irwwwan** [comment] 2018-01-19 14:20
The simplest thing you can do to solve that CUDA 8.0 support problem:
1. open "modules/cudalegacy/src/graphcuts.cpp"
2. change `#if !defined (HAVE_CUDA) || defined (CUDA_DISABLER)`
    to `#if !defined (HAVE_CUDA) || defined (CUDA_DISABLER) || (CUDART_VERSION >= 8000)`
Worked for me.
Hope it will save someone's day...

**Comment by guruvishnuvardan** [comment] 2018-02-10 10:15
I tried to change the code of graphcuts.cpp to the following, but the file is readonly

+#if !defined (HAVE_CUDA) || defined (CUDA_DISABLER) || (CUDART_VERSION >= 8000)

Can you please let me know what's the issue here is
