### ISSUE TITLE
Compiling with C Examples

### ISSUE THREAD

**Issue by pkajaba** [Itseez/opencv#6333] opened 2016-03-25 21:39 UTC
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

### Please state the information for your system
- OpenCV version: 3.1
- Host OS: Linux (Fedora 23) 
-  Compiler & CMake: GCC 5.3.1 & CMake 3.4.1

Problem with:
- C examples
When I try to compile this way : 
```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_C_EXAMPLES=1 ..
```
I got this error: http://pastebin.com/4bcJzke4

I have installed both v4l and v4l-devel.

Without tests it works OK

Thanks

**Comment by alalek** [comment] 2016-03-26 11:23
1) Attached log file is not enough (no real errors here, it is just set of checks). CMake **stdout** should be attached.
2) Looks like it is a duplicate of many issues with message:
```
CMake Error at samples/gpu/CMakeLists.txt:100 (list):
  list sub-command REMOVE_ITEM requires list to be present
```
It is already fixed in upstream ("master" branch)

**Closed by alalek** 2016-03-26 11:23 UTC
Labels: duplicate
