### ISSUE TITLE
VideoCapture and imread inconsistent with images

### ISSUE THREAD

**Issue by mbarnach** [Itseez/opencv#5225] opened 2015-08-20 10:03 UTC
When VideoCapture reads images, the images are not identical if they are read from a sequence pattern (aka %08d.jpg) or directly with imread (0000001.jpg).
The behavior could be highlight with this code snippet:

        cv::VideoCapture capture;
        bool ret = capture.open( "0000001.jpg" );
        //bool ret = capture.open( 0 );
        std::cout << "Video opened?: " << std::boolalpha << ret << std::endl;
        cv::Mat video_frame;
        if( ret )
        {
                capture >> video_frame;
        }

        cv::Mat image_frame = cv::imread( "00000001.jpg" );
        std::cout << "Image opened?: " << std::boolalpha << not image_frame.empty() << std::endl;

        cv::Mat diff;
        cv::cvtColor( video_frame, video_frame, cv::COLOR_BGR2GRAY );
        cv::cvtColor( image_frame, image_frame, cv::COLOR_BGR2GRAY );
        cv::absdiff( image_frame, video_frame, diff );
        std::cout << "Are images identical?: " << std::boolalpha << (0 == cv::countNonZero( diff ) ) << std::endl;

It returns false for the comparison. 
It returns true if images are both read by VideoCapture or imread.

**Comment by ilya-lavrenov** [comment] 2015-08-20 10:40
It can be caused by that `VideoCapture` and `imread` use different framework for image decoding. E.g. `VideoCapture` can use `GStreamer`, `imread` can use `libjpeg`.
You need to check whether `VideoCapture` is implemented as a sequence of `imread` call

**Comment by paroj** [comment] 2015-09-23 13:56
probably resolved by #4004

**Closed** 2015-10-12 12:08 UTC
Labels: affected: master, category: highgui-video, priority: normal, wontfix
