### ISSUE TITLE
Documentation error in description of fisheye project algorithm,

### ISSUE THREAD

**Issue by wcochran** [Itseez/opencv#6142] opened 2016-02-18 23:13 UTC
The documentation for fisheye::project algorithm has an error in it (I spent a day reimplementing
to figure this out).

On line 203 calib3d,hpp we have:
   ` \f[x' = (\theta_d / r) x \\ y' = (\theta_d / r) y \f]`

'x' and 'y' should be replaced with 'a' and 'b':
    `\f[x' = (\theta_d / r) a \\ y' = (\theta_d / r) b \f]`

This might save another poor soul later.

--wayne

**Comment by mshabunin** [comment] 2016-02-19 07:26
Duplicate of #6128

**Closed by mshabunin** 2016-02-19 07:26 UTC
Labels: duplicate
