### ISSUE TITLE
putText() Segmentation fault if string is empty

### ISSUE THREAD

**Issue by niksodu** [Itseez/opencv#5728] opened 2015-12-01 16:53 UTC
This simple code example ends in an Segmentation fault error.
```.cpp
Mat test(720, 1280, CV_8UC3);
string text = "";
putText(out, text, Point(10, 10), FONT_HERSHEY_SIMPLEX, 1.0, Scalar(0, 0, 0), 2);
```
The reason is the empty string (""), using any other string, that is not empty, works fine.
This did not happen in OpenCV 2.4.8.
Is this meant to work this way now, that one has to check the string if it is empty before drawing it?

**Comment by D-Alex** [comment] 2015-12-01 18:37
I guess your output image is not initialized and it has nothing to do with the string.
https://github.com/Itseez/opencv/blob/67ef84d883d43e795c2bf575a16719939f440ff1/modules/imgproc/src/drawing.cpp#L2158

**Comment by alalek** [comment] 2015-12-01 22:39
Looks like it is duplicate of #5451, which is already fixed in `master` branch.

**Comment by mshabunin** [comment] 2015-12-03 07:51
@niksodu , please provide more information about OpenCV version and platform. Also your example is not correct: `out` image does not exist.

**Closed** 2015-12-15 14:10 UTC
Labels: bug, category: imgproc, priority: low
