### ISSUE TITLE
BOWKMeansTrainer class is not available in even latest Opencv 3.1 java version

### ISSUE THREAD

**Issue by vishalezen** [Itseez/opencv#6478] opened 2016-04-26 15:41 UTC
BOWKMeansTrainer class is not available in even latest Opencv 3.1 java version

The same bug is raised for version 2.4.5 , 3 years ago available at link
http://code.opencv.org/issues/3003
by mohammag

No solution yet.

**Comment by jpaveggio** [comment] 2016-05-10 04:20
I have seen that both BOWTrainer, BOWKMeansTrainer and are BOWImgDescriptorExtractor. It is the quick solution I found, although the ideal would be the creation of the corresponding wrapper. Warning!! I have not tried the code yet!


[opencv-bof-java.zip](https://github.com/Itseez/opencv/files/256352/opencv-bof-java.zip)

**Comment by mshabunin** [comment] 2016-05-17 16:03
Duplicate of #4560

**Closed by mshabunin** 2016-05-17 16:03 UTC
