### ISSUE TITLE
Python binding: Add doxygen documentation contents to python doc strings

### ISSUE THREAD

**Issue by dov** [Itseez/opencv#6571] opened 2016-05-21 20:03 UTC
(This is a suggestion, so I took the freedom to erase all the bug related template code.)

The code below was tested with binding version 2.4.12.2 and the source code example was from git HEAD.

Currently the doc string only contains a terse syntax description. E.g.

    import cv2
    print cv2.setUseOptimized.__doc__
    setUseOptimized(onoff) -> None

But if you look at the h-file declaration for the corresponding function you have:

```
/** @brief Enables or disables the optimized code.

The function can be used to dynamically turn on and off optimized code (code that uses SSE2, AVX,
and other instructions on the platforms that support it). It sets a global flag that is further
checked by OpenCV functions. Since the flag is not checked in the inner OpenCV loops, it is only
safe to call the function on the very top level in your application where you can be sure that no
other OpenCV function is currently executed.

By default, the optimized code is enabled unless you disable it in CMake. The current status can be
retrieved using useOptimized.
@param onoff The boolean flag specifying whether the optimized code should be used (onoff=true)
or not (onoff=false).
 */
CV_EXPORTS_W void setUseOptimized(bool onoff);
```
I suggest to add to the python wrapper generator parsing of the entire doxygen string and conversion of its text to standard python strings. This will simplify interactive work as it will not be necessary to turn away from ipython (or any other doc sensitive IDE) in order to look up a description of what a function or method does.

**Comment by mshabunin** [comment] 2016-05-23 09:15
Looks like a duplicate of #4286.

**Closed by mshabunin** 2016-05-23 09:15 UTC
