### ISSUE TITLE
OpenCV 3.1.0 sets errno on successful imdecode

### ISSUE THREAD

**Issue by flx42** [Itseez/opencv#6120] opened 2016-02-16 00:27 UTC
Consider the following simple code where a cv::Mat object is created, encoded to a buffer and then decoded back again:
```
#include <errno.h>
#include <iostream>
#include <opencv2/highgui/highgui.hpp>

int main(int argc, char** argv)
{
    cv::Mat img1(64, 64, CV_8UC3, cv::Scalar(0,0,255));
    std::vector<uint8_t> buf;
    bool b = cv::imencode(".jpg", img1, buf);
    std::cout << "imencode: " << b << std::endl;

    std::cout << "errno before imdecode: " << errno << std::endl;
    cv::Mat img2 = cv::imdecode(buf, -1);
    std::cout << "errno after imdecode: " << errno << std::endl;
    std::cout << "img2: " << img2.rows << "x" << img2.cols << std::endl;
}
```
Compiled with:
```
g++ opencv.cc `pkg-config opencv --cflags --libs`
```

With OpenCV current master (d1a2c73228b) and with tag `3.1.0`, `errno` is set to `ENOENT` ("No such file or directory") after the call to `imdecode`. But the image is not empty, so the calls probably succeeded. This is the output:
```
imencode: 1
errno before imdecode: 0
errno after imdecode: 2
img2: 64x64
```
This code works fine with tag `3.0.0`.

How I compiled OpenCV:
```
git clone --depth 1 -b 3.1.0 https://github.com/Itseez/opencv.git opencv-3.1/
cd opencv-3.1/
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON \
      -DWITH_JPEG=ON -DBUILD_JPEG=ON -DWITH_PNG=ON -DBUILD_PNG=ON \
      -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DWITH_FFMPEG=OFF -DWITH_GTK=OFF \
      -DWITH_OPENCL=OFF -DWITH_QT=OFF -DWITH_V4L=OFF -DWITH_JASPER=OFF \
      -DWITH_1394=OFF -DWITH_TIFF=OFF -DWITH_OPENEXR=OFF -DWITH_IPP=OFF -DWITH_WEBP=OFF \
      -DBUILD_opencv_superres=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF \
      -DBUILD_opencv_videostab=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_flann=OFF \
      -DBUILD_opencv_ml=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_shape=OFF
sudo make install
```

**Comment by mshabunin** [comment] 2016-02-16 08:13
Is it a problem? As stated in [errno documentation](http://man7.org/linux/man-pages/man3/errno.3.html): 

> Its value is significant only when the return value of the call indicated an error 

And from [imdecode documentation](http://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga26a67788faa58ade337f8d28ba0eb19e&gsc.tab=0):

> If the buffer is too short or contains invalid data, the function returns an empty matrix (Mat::data==NULL)

**Comment by mshabunin** [comment] 2016-02-16 08:51
The cause of the problem is in the ExifReader which does not support working with images in memory.

**Comment by flx42** [comment] 2016-02-16 17:59
Thank you for your quick response @mshabunin 

> Is it a problem? As stated in errno documentation: [...]

Sure, but I was not expecting a C++ API call to set errno. We already have two ways to signal errors: return an empty matrix or raise an exception. Since errno is sticky, this can mess up with any code downstream.

> And from imdecode documentation:
> If the buffer is too short or contains invalid data, the function returns an empty matrix (Mat::data==NULL)

But the returned matrix is actually not empty. And if I examine the matrix it's perfectly valid as expected. I updated the original description with the output of my program, the result has the proper dimensions: `64x64`

> The cause of the problem is in the ExifReader which does not support working with images in memory.

Really? So why does the return matrix looks perfectly fine then?

**Comment by mshabunin** [comment] 2016-02-17 10:13
@flx42 , the issue should be fixed now, please check the latest master branch version.

>I'm confused, so why does the returned matrix looks perfectly fine then?

Because ExifReader is needed only for orientation tag handling and your image does not have one. I guess if you try to decode jpeg with a valid orientation tag from memory, the image will be rotated.

**Closed by mshabunin** 2016-02-17 10:13 UTC
Labels: bug, category: highgui-images, priority: low

**Comment by flx42** [comment] 2016-02-18 04:54
It works, thank you for the quick fix! And thank you for educating me :+1:
