### ISSUE TITLE
OpenCV 3 not detect VTK with QT 5

### ISSUE THREAD

**Issue by hyuce** [Itseez/opencv#6220] opened 2016-03-08 09:51 UTC
When I install OpenCV 3.1 (HEAD) with homebrew OpenCV not detect VTK. When I tried without QT 5 that is detect. 
Also says `Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!` and does not detect python3. 
my installation code is;
`brew -v install --with-contrib --with-cuda --with-ffmpeg --with-gphoto2 --with-gstreamer --with-java --with-libdc1394 --with-opengl --with-openni2 --with-python3 --with-qt --with-qt5 --with-vtk --with-tbb --without-tests --without-python  --HEAD opencv3`

### my system
- OpenCV version: 3.1(HEAD)
- Host OS: Mac OS X 10.11.3
- VTK Version : 7.1
- QT Version : 5

What is wrong and have any idea?

**Comment by alalek** [comment] 2016-03-08 10:14
We don't maintain homebrew OpenCV package.
Try to check issues list there and ask/report problem if nothing is found: https://github.com/Homebrew/homebrew-science/issues

1) VTK 7 - duplicate of #6180
2) Python message - external problem, seems not related to OpenCV, because we don't touch `PYTHONPATH`

**Closed** 2016-03-09 14:49 UTC
Labels: duplicate
